image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - akamud.vscode-theme-onedark
    - usernamehw.errorlens
    - akamud.vscode-theme-onedark
    - eamodio.gitlens
    - formulahendry.code-runner
    - golang.go
    - jock.svg
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - PKief.material-icon-theme
    - rangav.vscode-thunder-client
    - ritwickdey.LiveServer
    - rust-lang.rust-analyzer
    - vscode-icons-team.vscode-icons